.uno/CodeCompletion/ux14/ConfirmOrder.g.uno
.uno/CodeCompletion/ux14/MainView.g.uno
.uno/CodeCompletion/ux14/Delete.g.uno
.uno/CodeCompletion/ux14/Menu.g.uno
.uno/CodeCompletion/ux14/Order_Resources_res.g.uno
.uno/CodeCompletion/ux14/RobotoText.g.uno
.uno/CodeCompletion/ux14/OToggle.g.uno
.uno/CodeCompletion/ux14/UnconfirmOrder.g.uno
.uno/CodeCompletion/ux14/Order.unoproj.g.uno